version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_PASSWORD: app
      MYSQL_USER: app
      MYSQL_DB: app
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  php:
    build:
      context: ./api
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./api:/var/www/html
      - ~/.composer:/root/.composer
  ngnix:
    image: nginx:alpine
    volumes:
      - ./api:/var/www/html
      - ./front/nginx/www.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    ports:
      - 80:80
  redis:
    image: redis:6.0-rc-alpine
    command: --requirepass app
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 81:8080
volumes:
  db_data:
